-- V325 down
DROP TABLE IF EXISTS nd_inbox CASCADE;
DROP TABLE IF EXISTS nd_events CASCADE;
DROP TABLE IF EXISTS nd_extensions CASCADE;
DROP TABLE IF EXISTS nd_daily CASCADE;
DROP TABLE IF EXISTS nd_acks CASCADE;
DROP TABLE IF EXISTS nd_risk_closures CASCADE;
DROP TABLE IF EXISTS nd_permit_risks CASCADE;
DROP TABLE IF EXISTS nd_permit_equipment CASCADE;
DROP TABLE IF EXISTS nd_permit_crew CASCADE;
DROP TABLE IF EXISTS nd_permits CASCADE;
DROP TABLE IF EXISTS nd_risk_measures CASCADE;
DROP TABLE IF EXISTS nd_measure_catalog CASCADE;
DROP TABLE IF EXISTS nd_risk_catalog CASCADE;
DROP TABLE IF EXISTS nd_form_templates CASCADE;
